/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/config`; params?: Router.UnknownInputParams; } | { pathname: `/DarkModeContext`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/oldindex`; params?: Router.UnknownInputParams; } | { pathname: `/UserContext`; params?: Router.UnknownInputParams; } | { pathname: `/useStorageState`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin` | `/admin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/qrcode` | `/qrcode`; params?: Router.UnknownInputParams; } | { pathname: `/components/AdminUnlockPanel`; params?: Router.UnknownInputParams; } | { pathname: `/components/QRCodeGenerator`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useEmergencyService`; params?: Router.UnknownInputParams; } | { pathname: `/services/emergencyService`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/config`; params?: Router.UnknownOutputParams; } | { pathname: `/DarkModeContext`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/oldindex`; params?: Router.UnknownOutputParams; } | { pathname: `/UserContext`; params?: Router.UnknownOutputParams; } | { pathname: `/useStorageState`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/admin` | `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/qrcode` | `/qrcode`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AdminUnlockPanel`; params?: Router.UnknownOutputParams; } | { pathname: `/components/QRCodeGenerator`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useEmergencyService`; params?: Router.UnknownOutputParams; } | { pathname: `/services/emergencyService`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/config${`?${string}` | `#${string}` | ''}` | `/DarkModeContext${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/oldindex${`?${string}` | `#${string}` | ''}` | `/UserContext${`?${string}` | `#${string}` | ''}` | `/useStorageState${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/admin${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/qrcode${`?${string}` | `#${string}` | ''}` | `/qrcode${`?${string}` | `#${string}` | ''}` | `/components/AdminUnlockPanel${`?${string}` | `#${string}` | ''}` | `/components/QRCodeGenerator${`?${string}` | `#${string}` | ''}` | `/hooks/useEmergencyService${`?${string}` | `#${string}` | ''}` | `/services/emergencyService${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/config`; params?: Router.UnknownInputParams; } | { pathname: `/DarkModeContext`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/oldindex`; params?: Router.UnknownInputParams; } | { pathname: `/UserContext`; params?: Router.UnknownInputParams; } | { pathname: `/useStorageState`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin` | `/admin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/qrcode` | `/qrcode`; params?: Router.UnknownInputParams; } | { pathname: `/components/AdminUnlockPanel`; params?: Router.UnknownInputParams; } | { pathname: `/components/QRCodeGenerator`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useEmergencyService`; params?: Router.UnknownInputParams; } | { pathname: `/services/emergencyService`; params?: Router.UnknownInputParams; };
    }
  }
}
